services:
  - type: web
    name: db_posprojecthosting
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true

databases:
  - name: db_posprojecthosting
    databaseName: db_posprojecthosting
    user: db_user
    plan: free
